### ISSUE TITLE
Create a Cube Class

### ISSUE THREAD

**Issue by steffimhh** [Miles7up/raytracingPracticeExampleUR#2]
Derived class Cube from class AxisAlignedBoundingBox
- [ ] Implement method to get the planes of a cube
- [x] Override hashCode() // Key = minVector
- [x] Override equals()

**Comment by Miles7up** [comment]
> " ... Ist a die Kantenlänge, ... Die Diagonale von einer Ecke zur gegenüberliegenden hat jeweils die Länge Wurzel aus (a²+a²+a²)." http://mathepower.com/wuerfel.php --> Der min Punkt ist der hinten links vom Würfel, der max der vorne rechts --> der Punkt unter Max ergibt sich wenn die Länge der Seite vom y Wert des Max Punktes abgezogen wird usw.

**Comment by steffimhh** [comment]
dh. es würde sich für die Kantenlänge a ergeben, wenn d = Länge der Raumdiagonale:
 `a = d * Math.sqrt(1/3)`
